# Generated by Django 3.1.4 on 2021-04-24 09:28

from django.db import migrations, models
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_auto_20210423_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, upload_to=profile_page.models.banner_photo_upload),
        ),
    ]
