# Generated by Django 3.1.4 on 2021-04-25 10:20

from django.db import migrations, models
import django.db.models.deletion
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_profile_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(to='profile_page.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_profile', to='profile_page.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to=profile_page.models.post_photo_upload)),
                ('video', models.ImageField(blank=True, upload_to=profile_page.models.post_video_upload)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='profile_page.profile')),
                ('share_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_with', to='profile_page.circle')),
            ],
        ),
    ]
