# Generated by Django 3.1.4 on 2021-04-25 12:22

from django.db import migrations, models
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_auto_20210425_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to=profile_page.models.post_video_upload),
        ),
    ]
