# Generated by Django 3.1.4 on 2021-04-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_auto_20210425_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=5000),
        ),
    ]
