# Generated by Django 3.1.4 on 2021-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0007_auto_20210427_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='name',
            field=models.CharField(default='Default', max_length=20),
            preserve_default=False,
        ),
    ]
