# Generated by Django 3.1.4 on 2021-05-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('lb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.post')),
            ],
        ),
    ]
