# Generated by Django 3.1.4 on 2021-05-10 11:38

from django.db import migrations, models
import django.db.models.deletion
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0013_post_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=profile_page.models.story_image_upload)),
                ('video', models.ImageField(blank=True, upload_to=profile_page.models.story_video_upload)),
                ('caption', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile')),
            ],
        ),
    ]
