# Generated by Django 3.1.4 on 2021-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0014_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
