# Generated by Django 3.1.4 on 2021-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0015_auto_20210510_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=5000),
        ),
    ]
