# Generated by Django 3.1.7 on 2021-05-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_auto_20210515_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
