# Generated by Django 3.1.7 on 2021-05-21 11:29

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 21, 11, 29, 3, 444630, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
